---
- name: Install OpenJDK 17 on Ubuntu servers
  hosts: all
  become: yes
  tasks:
    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
