---
- name: Install Apache Maven on Ubuntu servers
  hosts: all
  become: yes
  tasks:
    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - unzip

    - name: Download Apache Maven
      get_url:
        url: https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip
        dest: /tmp/apache-maven-3.8.6-bin.zip

    - name: Extract Maven archive
      unarchive:
        src: /tmp/apache-maven-3.8.6-bin.zip
        dest: /opt/
        remote_src: yes

    - name: Create symlink for Maven
      file:
        src: /opt/apache-maven-3.8.6
        dest: /opt/maven
        state: link

    - name: Add Maven to PATH
      lineinfile:
        path: /etc/profile
        line: 'export MAVEN_HOME=/opt/maven'
        state: present

    - name: Update PATH environment variable
      lineinfile:
        path: /etc/profile
        line: 'export PATH=$MAVEN_HOME/bin:$PATH'
        state: present
        create: yes

    - name: Apply environment changes
      command: source /etc/profile
